package Exception;

public enum TypeException {
	BOARD_INCORECT_VALUES, DESIGN_WAS_NOT_SPECIFIED,COLOR_MAP_EMPTY, COLOR_MAP_TYPE, IMAGE_MAP_TYPE, IMAGE_MAP_EMPTY,
	STROKE_COLOR, STROKE_WIDTH,CELL_TYPE_UNDEFINED,
	BACKGROUND_BOARD_EMPTY, BACKGROUND_BORD_SIZE , BACKGROUND_BOARD_GRID, BACKGROUND_BOARD_TYPE,
	AGENT_BOARD_EMPTY, AGENT_BORD_SIZE , AGENT_BOARD_GRID, AGENT_BOARD_TYPE
}
