package Exception;

public enum TypeException {
	BOARD_INCORECT_VALUES, TYPE_BORD_SIZE ,DESIGN_WAS_NOT_SPECIFIED, TYPE_BOARD_GRID, COLOR_MAP_TYPE, IMAGE_MAP_TYPE, TYPE_BOARD_TYPE, STROKE_COLOR, STROKE_WIDTH
}
